# Generated by Django 5.2.4 on 2025-07-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("model_name", models.CharField(max_length=50)),
                ("image_name", models.CharField(max_length=255)),
                ("predicted_class", models.CharField(max_length=100)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
